services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    volumes:
      # use `docker-compose down --volumes` to remove the volumes
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=readings
      - POSTGRES_USER=readings
      - POSTGRES_DB=readings
volumes:
  postgres-data: